---
# The following role attempts to download any requested Intellij IDEA
# clients and configure them.

- name: Assert task variables
  tags: assert,jetbrains,intellij
  ansible.builtin.import_tasks: assertions/assert.yml
  run_once: yes
  delegate_to: localhost


- name: Download clients
  tags: software,download
  ansible.builtin.include_tasks: download.yml
  loop: "{{ intellij_clients }}"
  loop_control:
    loop_var: client
  when: intellij_clients | length > 0
