- name: "HTH | Intellij | Validate inputs"
  ansible.utils.validate:
    data: "{{ intellij }}"
    criteria: "{{ lookup('file', 'assertions/criteria/intellij-criteria.json') | from_json }}"
    engine: ansible.utils.jsonschema
  run_once: yes
  delegate_to: localhost
  when:
  - intellij is defined

- name: "HTH | Intellij | Manage clients"
  ansible.builtin.include_tasks: clients/main.yml
  loop: "{{ intellij.clients }}"
  loop_control:
    loop_var: client
